version: "3.7"

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis-cache:
    image: redis:alpine

  redis-queue:
    image: redis:alpine

  redis-socketio:
    image: redis:alpine

  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  frappe:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./apps:/home/frappe
    ports:
      - 8000:8000
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio